// Code generated by MockGen. DO NOT EDIT.
// Source: models/person.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "institute-person-api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPersonInterface is a mock of PersonInterface interface.
type MockPersonInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPersonInterfaceMockRecorder
}

// MockPersonInterfaceMockRecorder is the mock recorder for MockPersonInterface.
type MockPersonInterfaceMockRecorder struct {
	mock *MockPersonInterface
}

// NewMockPersonInterface creates a new mock instance.
func NewMockPersonInterface(ctrl *gomock.Controller) *MockPersonInterface {
	mock := &MockPersonInterface{ctrl: ctrl}
	mock.recorder = &MockPersonInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonInterface) EXPECT() *MockPersonInterfaceMockRecorder {
	return m.recorder
}

// GetAllNames mocks base method.
func (m *MockPersonInterface) GetAllNames() ([]models.PersonShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNames")
	ret0, _ := ret[0].([]models.PersonShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNames indicates an expected call of GetAllNames.
func (mr *MockPersonInterfaceMockRecorder) GetAllNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNames", reflect.TypeOf((*MockPersonInterface)(nil).GetAllNames))
}

// GetPerson mocks base method.
func (m *MockPersonInterface) GetPerson(id string) (models.PersonInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPerson", id)
	ret0, _ := ret[0].(models.PersonInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPerson indicates an expected call of GetPerson.
func (mr *MockPersonInterfaceMockRecorder) GetPerson(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPerson", reflect.TypeOf((*MockPersonInterface)(nil).GetPerson), id)
}

// PatchPerson mocks base method.
func (m *MockPersonInterface) PatchPerson(id string, body []byte, crumb *models.BreadCrumb) (models.PersonInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchPerson", id, body, crumb)
	ret0, _ := ret[0].(models.PersonInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchPerson indicates an expected call of PatchPerson.
func (mr *MockPersonInterfaceMockRecorder) PatchPerson(id, body, crumb interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchPerson", reflect.TypeOf((*MockPersonInterface)(nil).PatchPerson), id, body, crumb)
}

// PostPerson mocks base method.
func (m *MockPersonInterface) PostPerson(body []byte, crumb *models.BreadCrumb) (models.PersonInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostPerson", body, crumb)
	ret0, _ := ret[0].(models.PersonInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostPerson indicates an expected call of PostPerson.
func (mr *MockPersonInterfaceMockRecorder) PostPerson(body, crumb interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostPerson", reflect.TypeOf((*MockPersonInterface)(nil).PostPerson), body, crumb)
}
